### ISSUE TITLE
Invalid predicate error

### ISSUE THREAD

**Issue by steeni** [c3lang/c3-ts-mode#2]
I tried using this with the latest emacs version (built today from sources) but got the following error:

```bash
Invalid predicate, see ‘treesit-thing-settings’ for valid forms for a predicate: ("Invalid predicate, see `treesit-thing-settings' for valid forms of predicate" ("\\`\\(?:\\(?:bitstruct_declara\\|enum_declara\\|f\\(?:ault_declara\\|unc_defini\\)\\|\\(?:interface\\|macro\\|struct\\|union\\)_declara\\)tion\\)\\'"))
```

Here's how I tried to set it up:
```emacs-lisp
(defun my-c3-preferences ()
  (setq-local treesit-font-lock-level 4))

(use-package c3-ts-mode
  :vc (:url "https://github.com/c3lang/c3-ts-mode" :branch "main")
  :hook (c3-ts-mode . my-c3-preferences))
```

Occurred in a c3 example hello world program.
```c++
import std::io;

fn void main()
{
    io::printn("Hello, World!");
}
```

My tree-sitter library version is 0.24.3. I did install language grammar first ofcourse. TS-modes works with other modes (I tried c/c++ and dockerfile). Could be that it occurs for me because I'm using so new emacs, but figured to report this for you anyway.

**Comment by Nathan-Melaku** [comment]
I think this issue can be closed. now that the fix has been merged.
